# Generated by Django 3.1.4 on 2020-12-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20201222_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
